image:  
  name: hashicorp/terraform:light 
  entrypoint: [""] 
 
stages: 
  - start 
 
before_script: 
  - rm -rf .terraform 
  - echo $SERVICE_ACCOUNT_KEY > credentials_file.json 
  - terraform init 
 
build: 
  stage: start 
  script: 
    - terraform validate  
    - terraform plan -var="GCP_PROJECT_ID=$GCP_PROJECT_ID" 
    - terraform apply -var="GCP_PROJECT_ID=$GCP_PROJECT_ID" -auto-approve 
 
