services:
  - docker:dind
variables:
  DOCKER_HOST: tcp://docker:2375  
  DOCKER_TLS_CERTDIR: ""        
  REGION: "us-central1"                   
  SERVICE_NAME: "image-run"  

stages:
  - publish
  - deploy

publish:
  image: google/cloud-sdk:latest
  stage: publish
  before_script:
    - gcloud auth activate-service-account --key-file $SERVICE_ACCOUNT_KEY
    - gcloud auth configure-docker us.gcr.io

  script:
    - docker build -t $IMAGE_NAME .
    - docker tag $IMAGE_NAME "us.gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME"
    - docker push "us.gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME:latest"
  only:
    - main

deploy:
  image: google/cloud-sdk:latest
  stage: deploy
  before_script:
    - gcloud auth activate-service-account --key-file $SERVICE_ACCOUNT_KEY
    - gcloud auth configure-docker us.gcr.io
    - gcloud config set project $GCP_PROJECT_ID
  script:
   - gcloud run deploy --port 8000 $SERVICE_NAME --image "us.gcr.io/$GCP_PROJECT_ID/$IMAGE_NAME:latest" --platform managed --region $REGION --allow-unauthenticated 

  only:
    - main

